### ISSUE TITLE
Admin user continues to be present in Atlas Mongodb even after the service is deleted.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/mongodb-atlas#12]
**Steps to reproduce the problem:**
1. Deploy Atlas Mongodb service.
2. Once the app is deployed successfully, delete the service - `acorn rm -af mytest1.db`
3. Even after the service is deleted successfully, we Admin user continues to be present in Atlas Mongodb.

<img width="1067" alt="Screen Shot 2023-12-12 at 10 23 17 AM" src="https://github.com/acorn-io/mongodb-atlas/assets/122560863/44339d18-a086-4e53-ae4a-d1c8d5364374">

**Comment by lucj** [comment]
This will be done in PR#7, still under testing

**Comment by cloudnautique** [comment]
Should be resolved as long as the Acorn created it. 
If the user existed beforehand, then our behavior is to leave it alone.

**Comment by sangee2004** [comment]
1. Deploy Atlas Mongodb service without passing clusterName parameter.
2. Once the app is deployed successfully, delete the service - `acorn rm -af mytest1.db`

Admin user now gets deleted as expected.
