### ISSUE TITLE
Not able to deploy service with "M10" tier. 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/mongodb-atlas#15]
**Steps to reproduce the problem:**

 Atlas Mongo DB service - commit-id `aec31c70c9bf`

1. Deploy Atlas Mongo DB service using `--tier M10` option.

App deployment fails with following error:

```
create-cluster-8wcrg.create-cluster: -> cluster sangeetest does not exist
create-cluster-pd28w.create-cluster: Error: bad flag syntax: ----diskSizeGB
create-cluster-8wcrg.create-cluster: -> about to create cluster sangeetest of type M10 in AZURE / US_EAST_2
create-cluster-msjjw.create-cluster: -> about to create cluster sangeetest of type M10 in AZURE / US_EAST_2
create-cluster-msjjw.create-cluster: Error: bad flag syntax: ----diskSizeGB
create-cluster-8wcrg.create-cluster: Error: bad flag syntax: ----diskSizeGB
```

**Note** -  Able to deploy service using `--tier M2` option.

**Comment by lucj** [comment]
The additional "--" for the diskSizeDB params will be removed.

**Comment by lucj** [comment]
Could you confirm this is ok now ?

**Comment by sangee2004** [comment]
Able to deploy service with "M10" tier successfully now.
