### ISSUE TITLE
Not able to pick MongoDB version by setting - `dbVersion` param.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/mongodb-atlas#16]
**Steps to reproduce the problem:**
1. Deploy Atlas Mongodb app with a specific db version using `dbVersion` param -
`acorn run --update -n santest1 . --clusterName sangeedbversion --dbName sandb --dbUser sanuser1 --dbVersion 7.0 --provider AZURE --region US_EAST_2 `        

2. Once the app is deployed , dbVersion always shows - as "6.0.12" in Atlas console

<img width="1169" alt="Screen Shot 2023-12-12 at 2 57 43 PM" src="https://github.com/acorn-io/mongodb-atlas/assets/122560863/9f6c029b-0891-48ec-afde-418be506bec7">

<img width="906" alt="Screen Shot 2023-12-12 at 3 01 48 PM" src="https://github.com/acorn-io/mongodb-atlas/assets/122560863/89836d13-9108-4a3a-81b3-cf3bb7b285c1">

**Comment by cloudnautique** [comment]
Per the docs, that checks out. https://www.mongodb.com/docs/atlas/reference/faq/database/#which-versions-of-mongodb-do-service-clusters-use-

Please try on an m10+ cluster.

**Comment by sangee2004** [comment]
Will try this on M10 clusters once https://github.com/acorn-io/mongodb-atlas/issues/15 is addressed

**Comment by sangee2004** [comment]
Able to set DB version using `dbVesion` param for clusters with M10 tier.
